name: ECS Deployment

on:
  workflow_dispatch: # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Get ECS service ARN
        run: |
          echo "ECS_SERVICE_ARN=$(aws ecs list-services --cluster gateway --query 'serviceArns[?contains(@, "frontend")]' --output text)" >> $GITHUB_ENV


      - name: Get existing task definition ARN
        run: |
          echo "task_arn=$(aws ecs describe-services --cluster gateway --services "${ECS_SERVICE_ARN}" --query "services[0].taskDefinition" --output text)"  >> $GITHUB_ENV 

      - name: Get task definition details
        run: |
          echo "task_details=$(aws ecs describe-task-definition --task-definition "$task_arn")"  >> $GITHUB_ENV

      - name: Get execution role ARN
        run: |
          echo "execution_role_arn=$(echo "$task_details" | jq -r '.taskDefinition.executionRoleArn')"  >> $GITHUB_ENV

      - name: Load JSON content from GitHub Actions secret
        run: |
          echo "${{ secrets.YOUR_JSON_SECRET }}" > task_definition.json

      - name: Modify task definition JSON with new image
        run: |
          branch_name=$(echo "${GITHUB_REF#refs/heads/}")
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV
          sed -i 's/"image": "NEW_IMAGE",/"image": "058264075488.dkr.ecr.eu-central-1.amazonaws.com\/frontend:main",/g' task_definition.json          cat task_definition.json
      - name: Register new task definition
        run: |
          # Register the new task definition
          cat task_definition.json
          register_response=$(aws ecs register-task-definition --cli-input-json file://task_definition.json)

          # Extract the new task definition ARN
          new_task_arn=$(echo "$register_response" | jq -r '.taskDefinition.taskDefinitionArn')

          # Update the ECS service with the new task definition
          echo "Updating service with new task definition..."
          aws ecs update-service --cluster gateway --service "${ECS_SERVICE_ARN}" --task-definition "$new_task_arn" --force-new-deployment

        env:
          NEW_IMAGE: ${{ github.event.head_commit.id }}
