name: ECS Deployment

on:
  workflow_dispatch: # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get ECS Service ARN
        id: get_service_arn
        run: |
          echo "ECS_SERVICE_ARN=$(aws ecs list-services --cluster gateway --query "serviceArns[?contains(@, 'frontend')]" --output text)" >> $GITHUB_ENV

      - name: Extract Cluster and Account ID
        id: extract_ids
        run: |
          echo "CLUSTER=${{ secrets.CLUSTER }}" >> $GITHUB_ENV
          echo "ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}" >> $GITHUB_ENV

      - name: Get branch name
        id: branch_name
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create new image name
        id: new_image
        run: |
          BRANCH_NAME=${{ steps.branch_name.outputs.BRANCH_NAME }}
          echo "NEW_IMAGE=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}/frontend:$BRANCH_NAME" >> $GITHUB_ENV

      - name: Deploy to ECS
        run: |
          # Get task definition associated with the service
          echo ECS_SERVICE_ARN $ECS_SERVICE_ARN
          task_arn=$(aws ecs describe-services --cluster $CLUSTER --services "${ECS_SERVICE_ARN}" --query "services[0].taskDefinition" --output text)
          echo $task_arn 
          
          # Get task definition details
          task_details=$(aws ecs describe-task-definition --task-definition "$task_arn")

          # Extract image from the task definition
          current_image=$(echo "$task_details" | jq -r '.taskDefinition.containerDefinitions[0].image')

          # Compare current and new image
          if [ "$current_image" = "$NEW_IMAGE" ]; then
              echo "Image is already up to date. Updating service..."
              aws ecs update-service --cluster $CLUSTER --service "${ECS_SERVICE_ARN}" --force-new-deployment
          else
              echo "Creating new revision with the new image and deploying..."
              # Update task definition with new image
              new_task_definition=$(echo "$task_details" | jq --arg new_image "$NEW_IMAGE" '.taskDefinition | .containerDefinitions[0].image = $new_image')
              # Register new task definition
              new_task_arn=$(aws ecs register-task-definition --cli-input-json "$new_task_definition" --query "taskDefinition.taskDefinitionArn" --output text)
              # Update service with new task definition
              aws ecs update-service --cluster $CLUSTER --service "${ECS_SERVICE_ARN}" --task-definition "$new_task_arn" --force-new-deployment
          fi
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
