name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: webfactory/ssh-agent@v0.8.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nuraly/frontend
    - name: Save the docker image
      run: docker save -o frontend.tar nuraly/frontend
    - name: list test
      run: ls
    - name : copy to remote
      run: scp -o StrictHostKeyChecking=no  frontend.tar root@${{ secrets.MAIN_HOST }}:/home/images
    - name : load image into docker
      run: ssh -o StrictHostKeyChecking=no  root@${{ secrets.MAIN_HOST }} "cd /home/images && docker load -i frontend.tar"

      
