import { html, LitElement, css, nothing } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import type { ColumnDTO } from '../../../runtime/redux/store/database';
import '../../../runtime/components/ui/nuraly-ui/src/components/input/input.component';
import '../../../runtime/components/ui/nuraly-ui/src/components/checkbox/checkbox.component';
import '../../../runtime/components/ui/nuraly-ui/src/components/datepicker/datepicker.component';
import '../../../runtime/components/ui/nuraly-ui/src/components/select/select.component';

function getInputKind(columnType: string): 'text' | 'number' | 'boolean' | 'date' | 'datetime' | 'json' {
  const lower = columnType.toLowerCase();
  if (['integer', 'int', 'int4', 'int8', 'bigint', 'smallint', 'decimal', 'numeric',
       'real', 'double precision', 'float', 'float4', 'float8', 'money'].some(t => lower === t || lower.startsWith(t))) {
    return 'number';
  }
  if (lower === 'boolean' || lower === 'bool') return 'boolean';
  if (lower === 'date') return 'date';
  if (['timestamp', 'timestamptz', 'datetime'].some(t => lower.startsWith(t)) || lower.startsWith('time')) return 'datetime';
  if (lower === 'json' || lower === 'jsonb') return 'json';
  return 'text';
}

function isAutoGenerated(col: ColumnDTO): boolean {
  if (!col.primaryKey) return false;
  const lower = col.type.toLowerCase();
  if (['serial', 'bigserial', 'smallserial'].includes(lower)) return true;
  const def = (col.defaultValue || '').toLowerCase();
  if (def.includes('nextval') || def.includes('auto_increment') || def.includes('generated')) return true;
  return false;
}

function isRequired(col: ColumnDTO): boolean {
  if (isAutoGenerated(col)) return false;
  return !col.nullable && !col.defaultValue;
}

@customElement('insert-row-panel')
export class InsertRowPanel extends LitElement {
  static override styles = css`
    :host {
      position: absolute;
      z-index: 200;
      width: 320px;
      max-height: 500px;
      background: var(--n-color-surface, #fff);
      border: 1px solid var(--n-color-border, #e5e7eb);
      border-radius: 8px;
      overflow: hidden;
      display: flex;
      flex-direction: column;
      box-shadow: 0 8px 24px rgba(0, 0, 0, 0.12);
    }

    /* ── Header ── */
    .config-panel-header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 12px;
      border-bottom: 1px solid var(--n-color-border, #e5e7eb);
      background: var(--n-color-surface-secondary, #f9fafb);
    }

    .config-panel-title {
      display: flex;
      align-items: center;
      gap: 8px;
      font-size: 13px;
      font-weight: 600;
      color: var(--n-color-text, #111827);
    }

    .config-panel-close {
      background: none;
      border: none;
      color: var(--n-color-text-muted, #6b7280);
      cursor: pointer;
      padding: 4px;
      display: flex;
      align-items: center;
      justify-content: center;
      border-radius: 4px;
      transition: all 0.15s ease;
      font-size: 18px;
      line-height: 1;
    }

    .config-panel-close:hover {
      color: var(--n-color-text, #111827);
      background: var(--n-color-surface-hover, #f3f4f6);
    }

    /* ── Scrollable content ── */
    .config-panel-content {
      flex: 1;
      overflow-y: auto;
      padding: 12px;
      display: flex;
      flex-direction: column;
      gap: 12px;
      overscroll-behavior: contain;
    }

    /* ── Sections ── */
    .config-section {
      padding-top: 8px;
      border-top: 1px solid var(--n-color-border, #e5e7eb);
      display: flex;
      flex-direction: column;
      gap: 12px;
    }

    .config-section:first-child {
      padding-top: 0;
      border-top: none;
    }

    .config-section-header {
      display: flex;
      flex-direction: column;
      gap: 4px;
    }

    .config-section-title {
      font-size: 10px;
      font-weight: 600;
      color: var(--n-color-text-muted, #6b7280);
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }

    .config-section-desc {
      font-size: 11px;
      color: var(--n-color-text-muted, #9ca3af);
    }

    /* ── Fields ── */
    .config-field {
      display: flex;
      flex-direction: column;
      gap: 4px;
    }

    .config-field label {
      font-size: 11px;
      font-weight: 500;
      color: var(--n-color-text-muted, #6b7280);
      text-transform: uppercase;
      letter-spacing: 0.5px;
      display: flex;
      align-items: center;
      gap: 6px;
    }

    .config-field nr-input,
    .config-field nr-datepicker,
    .config-field nr-select {
      width: 100%;
    }

    .field-description {
      font-size: 11px;
      color: var(--n-color-text-muted, #9ca3af);
      margin-top: 4px;
    }

    .col-type {
      font-weight: 400;
      text-transform: none;
      letter-spacing: 0;
      color: var(--n-color-text-muted, #9ca3af);
    }

    .required-mark {
      color: var(--n-color-error, #ef4444);
      font-weight: 600;
    }

    .checkbox-field {
      display: flex;
      align-items: center;
      padding-top: 2px;
    }

    /* ── Footer ── */
    .panel-footer {
      display: flex;
      gap: 8px;
      padding: 12px;
      border-top: 1px solid var(--n-color-border, #e5e7eb);
    }

    .btn {
      flex: 1;
      padding: 8px 12px;
      border-radius: 6px;
      font-size: 13px;
      font-weight: 500;
      cursor: pointer;
      border: none;
      transition: all 0.15s ease;
      text-align: center;
    }

    .btn-cancel {
      background: var(--n-color-surface, #fff);
      color: var(--n-color-text, #111827);
      border: 1px solid var(--n-color-border, #e5e7eb);
    }

    .btn-cancel:hover {
      background: var(--n-color-surface-hover, #f9fafb);
    }

    .btn-insert {
      background: var(--n-color-primary, #3b82f6);
      color: white;
    }

    .btn-insert:hover {
      background: var(--n-color-primary-dark, #2563eb);
    }

    .btn-insert:disabled {
      opacity: 0.5;
      cursor: not-allowed;
    }

    /* ── Result banners ── */
    .result-success {
      padding: 10px 12px;
      background: var(--n-color-success-bg, #f0fdf4);
      border: 1px solid #bbf7d0;
      border-radius: 6px;
      color: var(--n-color-success, #16a34a);
      font-size: 12px;
    }

    .result-error {
      padding: 10px 12px;
      background: var(--n-color-error-bg, #fef2f2);
      border: 1px solid #fecaca;
      border-radius: 6px;
      color: var(--n-color-error, #ef4444);
      font-size: 12px;
      word-break: break-word;
    }

    .empty-state {
      padding: 24px;
      text-align: center;
      color: var(--n-color-text-muted, #9ca3af);
      font-size: 13px;
    }
  `;

  @property({ type: String }) tableName = '';
  @property({ type: String }) schemaName = '';
  @property({ type: Array }) columns: ColumnDTO[] = [];

  @state() private fieldValues: Record<string, any> = {};
  @state() private inserting = false;
  @state() private result: { success: boolean; error?: string; affectedRows?: number } | null = null;

  private get editableColumns(): ColumnDTO[] {
    return this.columns.filter(col => !isAutoGenerated(col));
  }

  private handleFieldChange(columnName: string, value: any) {
    this.fieldValues = { ...this.fieldValues, [columnName]: value };
  }

  private handleInsert() {
    const fields: Record<string, any> = {};
    for (const col of this.editableColumns) {
      const value = this.fieldValues[col.name];
      if (value !== undefined && value !== '' && value !== null) {
        fields[col.name] = value;
      }
    }

    this.inserting = true;
    this.result = null;
    this.dispatchEvent(new CustomEvent('insert-row', {
      bubbles: true,
      composed: true,
      detail: { fields },
    }));
  }

  private handleClose() {
    this.result = null;
    this.dispatchEvent(new CustomEvent('close-insert-panel', { bubbles: true, composed: true }));
  }

  public setResult(result: { success: boolean; error?: string; affectedRows?: number }) {
    this.inserting = false;
    this.result = result;
    if (result.success) {
      this.fieldValues = {};
    }
  }

  public resetState() {
    this.inserting = false;
    this.result = null;
    this.fieldValues = {};
  }

  private renderField(col: ColumnDTO) {
    const kind = getInputKind(col.type);
    const required = isRequired(col);
    const value = this.fieldValues[col.name];
    const hint = col.defaultValue ? `Default: ${col.defaultValue}` : col.nullable ? 'Optional' : '';

    return html`
      <div class="config-field">
        <label>
          ${col.name}
          <span class="col-type">${col.type}</span>
          ${required ? html`<span class="required-mark">*</span>` : nothing}
        </label>

        ${kind === 'boolean' ? html`
          <div class="checkbox-field">
            <nr-checkbox
              ?checked=${value === true || value === 'true'}
              @nr-change=${(e: CustomEvent) => this.handleFieldChange(col.name, e.detail?.checked ?? (e.target as any)?.checked)}
            ></nr-checkbox>
          </div>
        ` : kind === 'date' || kind === 'datetime' ? html`
          <nr-datepicker
            .value=${value || ''}
            placeholder=${kind === 'datetime' ? 'YYYY-MM-DD HH:mm:ss' : 'YYYY-MM-DD'}
            @nr-change=${(e: CustomEvent) => this.handleFieldChange(col.name, e.detail?.value ?? (e.target as any)?.value)}
          ></nr-datepicker>
        ` : kind === 'number' ? html`
          <nr-input
            type="number"
            .value=${value != null ? String(value) : ''}
            placeholder=${`Enter ${col.name}`}
            @nr-input=${(e: CustomEvent) => {
              const raw = e.detail?.value ?? (e.target as any)?.value;
              this.handleFieldChange(col.name, raw !== '' ? Number(raw) : '');
            }}
          ></nr-input>
        ` : kind === 'json' ? html`
          <nr-input
            .value=${value || ''}
            placeholder='{"key": "value"}'
            @nr-input=${(e: CustomEvent) => this.handleFieldChange(col.name, e.detail?.value ?? (e.target as any)?.value)}
          ></nr-input>
        ` : html`
          <nr-input
            .value=${value || ''}
            placeholder=${`Enter ${col.name}`}
            @nr-input=${(e: CustomEvent) => this.handleFieldChange(col.name, e.detail?.value ?? (e.target as any)?.value)}
          ></nr-input>
        `}

        ${hint ? html`<span class="field-description">${hint}</span>` : nothing}
      </div>
    `;
  }

  override render() {
    return html`
      <div class="config-panel-header">
        <span class="config-panel-title">Insert — ${this.tableName}</span>
        <button class="config-panel-close" @click=${this.handleClose}>&times;</button>
      </div>

      <div class="config-panel-content">
        ${this.editableColumns.length === 0 ? html`
          <div class="empty-state">No editable columns found for this table.</div>
        ` : html`
          <div class="config-section">
            <div class="config-section-header">
              <span class="config-section-title">Column Values</span>
              <span class="config-section-desc">Fill in values for the new row</span>
            </div>
            ${this.editableColumns.map(col => this.renderField(col))}
          </div>
        `}

        ${this.result ? html`
          <div class="config-section">
            ${this.result.success ? html`
              <div class="result-success">
                Row inserted${this.result.affectedRows ? ` (${this.result.affectedRows} row)` : ''}
              </div>
            ` : html`
              <div class="result-error">${this.result.error || 'Insert failed'}</div>
            `}
          </div>
        ` : nothing}
      </div>

      <div class="panel-footer">
        <button class="btn btn-cancel" @click=${this.handleClose} ?disabled=${this.inserting}>
          Cancel
        </button>
        <button
          class="btn btn-insert"
          @click=${this.handleInsert}
          ?disabled=${this.inserting || this.editableColumns.length === 0}
        >
          ${this.inserting ? 'Inserting...' : 'Insert'}
        </button>
      </div>
    `;
  }
}
