quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/functions_dev
nuraly.functions.template.base.path=/app/templates
DOCKER_HOST=unix:///var/run/docker.sock

quarkus.datasource.devservices.port=5433
quarkus.hibernate-orm.database.generation = update
%dev.quarkus.hibernate-orm.database.generation = update
quarkus.http.port=7001
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/api/v1/functions/swagger-ui
quarkus.http.cors.origins=*
quarkus.http.cors=true
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.hibernate-orm.jdbc.lob.non-contextual-creation=true
nuraly-registry-service.url=registry.nuraly.io
nuraly-registry-service.username=nuraly
nuraly-registry-service.password=nuraly
nuraly-functions.domain=default.192.168.49.2.sslip.io
nuraly-functions.port=32437
nuraly-functions.gateway-host=192.168.49.2
permissions.api.url=http://localhost/api/permissions/has
# Disable permissions in dev mode (set to true in production)
%dev.permissions.enabled=false
permissions.enabled=true

# Index the shared permission library for CDI/JAX-RS discovery
quarkus.index-dependency.permission-lib.group-id=com.github.Nuralyio
quarkus.index-dependency.permission-lib.artifact-id=shared-java-library
