apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app51-second
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: registry.nuraly.io/51-second
        imagePullPolicy: Always
        env:
            - name: TARGET
              value: "lol"

       
