
worker_processes 1;

error_log  logs/error.log;
error_log  logs/error.log  notice;
error_log logs/error.log info;


include config/env-vars.conf;

include config/events.conf;


http {
    include config/http.conf;
    
    include config/upstreams/ec2-env-upstreams.conf;

    server {
        listen 80;

        include config/redis.conf;

        # Custom error pages
        error_page 500 /errors/500.html;
        error_page 502 /errors/502.html;
        error_page 503 504 /errors/500.html;

        location /errors/ {
            alias /usr/local/openresty/nginx/conf/errors/;
            internal;
        }

        include locations/locations.conf;

    }
    include /etc/nginx/conf.d/*.conf;
}