
worker_processes auto;

error_log  logs/error.log;
error_log  logs/error.log  notice;
error_log logs/error.log info;


include config/env-vars.conf;

include config/events.conf;


http {
    include config/http.conf;
    
    include config/upstreams/fully-env-upstreams.conf;

    server {
        listen 80;

        include config/redis.conf;

        include locations/locations.conf;

    }
    include /etc/nginx/conf.d/*.conf;
}