
worker_processes 1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
error_log logs/error.log info;


include config/env-vars.conf;

include config/events.conf;

include config/upstreams/backend-env-upstreams.conf;

http {
    include config/http.conf;

    server {
        listen 80;

        include config/redis.conf;

        include locations/locations.conf;

    }
    include /etc/nginx/conf.d/*.conf;
}