version: '3.4'

services:
  
  pgadmin:
    extends:
      file: docker-compose-common.yml
      service: pgadmin

  redis:
    extends:
      file: docker-compose-common.yml
      service: redis

  postgres:
    extends:
      file: docker-compose-common.yml
      service: postgres
  keycloak:
    extends:
      file: docker-compose-common.yml
      service: keycloak   
  rabbitmq:
    extends:
      file: docker-compose-common.yml
      service: rabbitmq   
  copilot:
    extends:
      file: docker-compose-common.yml
      service: copilot   

  nginx:
    build:
      context:  ./Nginx
      dockerfile: Dockerfile
    environment:
      KEYCLOAK_HOST :  ${KEYCLOAK_HOST:-localhost} 
      KEYCLOAK_REALM : ${KEYCLOAK_REALM:-nuraly} 
      KEYCLOAK_CLIENT_ID :  ${KEYCLOAK_CLIENT_ID:-nuraly-stage} 
      KEYCLOAK_CLIENT_SECRET :  ${KEYCLOAK_CLIENT_SECRET:-z49EYGt6w3zp0VaiYC14CoN5vkCnDFqJ} 
      KEYCLOAK_SCHEME :  ${KEYCLOAK_SCHEME:-http} 
      KEYCLOAK_FULLURL :  ${KEYCLOAK_FULLURL:-http://localhost} 
      DOMAIN :  ${HOST_DOMAIN:-localhost} 
      KC_HOSTNAME: ${KC_HOSTNAME:-localhost} 
      CHAT_HOSTNAME: ${CHAT_HOSTNAME:-chat.copilot.tn:6900}
    volumes:
      - ./Nginx/nginx-fully.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./Nginx/errors:/usr/local/openresty/nginx/conf/errors
    ports:
      - 80:80
    depends_on:
      - redis
  # nuraly_services:
  #     build:
  #       context:  ../backend
  #       dockerfile: Dockerfile
  #     ports:
  #       - "${SERVICES_PORT:-8081}:8081"
  #     environment:
  #       KEYCLOAK_REALM : ${KEYCLOAK_REALM:-nuraly} 
  #       KEYCLOAK_CLIENT_ID :  ${KEYCLOAK_CLIENT_ID:-nuraly-stage} 
  #       KEYCLOAK_CLIENT_SECRET :  ${KEYCLOAK_CLIENT_SECRET:-xyzzyQs2uEdo6yAHw4pQiqQoDudXlMA2} 
  #     env_file:
  #     - .env.default
  #     - .env
volumes:
 pgadmin-data:
 postgres-data:
 infinispan_data:
