version: '3.4'

services:
  
  pgadmin:
    extends:
      file: docker-compose-common.yml
      service: pgadmin

  redis:
    extends:
      file: docker-compose-common.yml
      service: redis

  nginx:
    build:
      context:  ./Nginx
      dockerfile: Dockerfile
    environment:
      KEYCLOAK_HOST :  ${KEYCLOAK_HOST:-localhost} 
      KEYCLOAK_REALM : ${KEYCLOAK_REALM:-nuraly} 
      KEYCLOAK_CLIENT_ID :  ${KEYCLOAK_CLIENT_ID:-nuraly-stage} 
      KEYCLOAK_CLIENT_SECRET :  ${KEYCLOAK_CLIENT_SECRET:-xyzzyQs2uEdo6yAHw4pQiqQoDudXlMA2} 
      KEYCLOAK_SCHEME :  ${KEYCLOAK_SCHEME:-http} 
      DOMAIN :  ${HOST_DOMAIN:-localhost} 
      KC_HOSTNAME: ${KC_HOSTNAME:-nuraly.io} 
    volumes:
      - ./Nginx/nginx-fully.conf:/usr/local/openresty/nginx/conf/nginx.conf
    ports:
      - 80:80
    depends_on:
      - redis
  
volumes:
 pgadmin-data:
