version: '3.4'

services:

  postgres:
    extends:
      file: docker-compose-common.yml
      service: postgres

  
  pgadmin:
    extends:
      file: docker-compose-common.yml
      service: pgadmin

  nginx:
    extends:
      file: docker-compose-common.yml
      service: nginx

  keycloak_pg:
      extends:
        file: docker-compose-common.yml
        service: keycloak_pg

  redis:
    extends:
      file: docker-compose-common.yml
      service: redis

  memcached: 
    extends:
      file: docker-compose-common.yml
      service: memcached

    
  keycloak:
      extends:
        file: docker-compose-common.yml
        service: keycloak

volumes:
  postgres-data:
  pgadmin-data:
  keycloak-db-data:
  redis-data:
