sonar.projectKey=nuralyio_kv
sonar.projectName=Nuraly KV
sonar.organization=nuralyio

# Source code
sonar.sources=src/main/java

# Compiled classes (required for Java analysis)
sonar.java.binaries=target/classes

# Exclude test and generated files from analysis
sonar.exclusions=**/target/**,**/*.xml

# Coverage
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
