location /auth {
    set $target $upstream_keycloak;
    proxy_pass $target;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Scheme $scheme;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    set $target_scheme '';

    access_by_lua_block {
        local host = os.getenv("KC_HOSTNAME")
        ngx.log(ngx.INFO, host)
        if host == "localhost" then
        ngx.var.target_scheme = "http"
        else
        ngx.var.target_scheme = "https"
        end
    }

    proxy_set_header X-Forwarded-Proto $target_scheme;
    client_max_body_size 0;

}

location /logout {
    access_by_lua_block {
        require("main").logout()
    }
}

location /cb {
    access_by_lua_block {
        require("main").authenticateWithKeycloak()
    }
    set $target $upstream_keycloak;
    proxy_pass $target;
}


location /get-user-info {
    set $user_ids_to_retrieve "";
    content_by_lua_block {
        ngx.req.read_body()
        local post_data = ngx.req.get_body_data()
        ngx.var.user_ids_to_retrieve = post_data
        require("userinfo")
    }

}
