
location /api/v1/functions {
    access_by_lua_block {
        require("main").authenticateWithKeycloakPass(nil)

    }
    proxy_pass http://functions-api/api/v1/functions;
    proxy_redirect off;
    proxy_cache_bypass $http_upgrade;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection keep-alive;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $server_name;
}

location /api {
    access_by_lua_block {
        require("main").authenticateWithKeycloakPass(nil)

    }
    proxy_pass http://services-api;
    proxy_redirect off;
    proxy_cache_bypass $http_upgrade;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection keep-alive;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $server_name;
}

location ~* ^/(api/chat|api/chats) {
    set $chat_hostname '';

    access_by_lua_block {
        local chat_hostname = os.getenv("CHAT_HOSTNAME")
        ngx.log(ngx.INFO, "Chat hostname: ", chat_hostname)
        if chat_hostname then
            ngx.var.chat_hostname = chat_hostname
        else
            ngx.var.chat_hostname = "default_chat_hostname"  -- Provide a default value
            ngx.log(ngx.ERR, "CHAT_HOSTNAME environment variable is not set. Using default value.")
        end
        -- Log chat hostname
        ngx.log(ngx.INFO, "Chat hostname: ", ngx.var.chat_hostname)
    }

    access_log /var/log/openresty-chat.log;
    error_log /var/log/openresty-chat_error.log;

    proxy_pass http://$chat_hostname;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    client_max_body_size 0;

    # Additional security headers (optional)
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
}

