###
# Default main location block
# This block is used to proxy all requests to the front service
# The front service is the service that serves the front end of the application
###

location = / {
    # Pass the rewritten request to the front service
    proxy_pass http://front/app/view/8639f6d5-9171-41e4-a21c-447c8c1b62c2;
    proxy_buffering off;
    proxy_redirect off;
    proxy_connect_timeout 65s;
    proxy_send_timeout 60s;
    proxy_read_timeout 60s;
    proxy_cache_bypass $http_upgrade;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_http_version 1.1;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
}

location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|astro|mjs|ts)$ {
    proxy_pass http://front;
    proxy_buffering off;
    proxy_redirect off;
    proxy_cache_bypass $http_upgrade;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

location ~* ^/@ {
    proxy_pass http://front;
}