###
# Default main location block
# This block is used to proxy all requests to the front service
# The front service is the service that serves the front end of the application
###

location / {
    access_by_lua_block {
        require("main").authenticateWithKeycloakPass(nil)

    }
    # Pass the rewritten request to the front service
    proxy_pass http://front/;
    proxy_buffering off;
    proxy_redirect off;
    proxy_cache_bypass $http_upgrade;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_http_version 1.1;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
}
