name: Deplpoy CI

on:
  workflow_dispatch:
jobs:

  build_keyclack:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: webfactory/ssh-agent@v0.8.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name : copy to remote
      run:  |
        scp -o StrictHostKeyChecking=no  docker-compose-common.yml root@${{ secrets.MAIN_HOST }}:/root/docker-compose
        scp -o StrictHostKeyChecking=no  docker-compose.yml root@${{ secrets.MAIN_HOST }}:/root/docker-compose
    - name : load image into docker
      run: ssh -o StrictHostKeyChecking=no  root@${{ secrets.MAIN_HOST }} "cd /root/docker-compose && docker compose up"
