name: Deplpoy CI

on:
  workflow_dispatch:
jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: webfactory/ssh-agent@v0.8.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name : copy to docker compose files to remote host
      run:  |
        scp -o StrictHostKeyChecking=no  docker-compose-common.yml ec2-user@${{ secrets.MAIN_HOST }}:/home/docker-compose
        scp -o StrictHostKeyChecking=no  docker-compose.yml ec2-user@${{ secrets.MAIN_HOST }}:/home/docker-compose
        scp -o StrictHostKeyChecking=no  docker-compose-down.sh ec2-user@${{ secrets.MAIN_HOST }}:/home/docker-compose
    - name : Run docker compose on the remote host
      run: ssh -o StrictHostKeyChecking=no  ec2-user@${{ secrets.MAIN_HOST }} "cd /home/docker-compose && ./docker-compose-down.sh && docker compose up -d"
