name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_keyclack:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: webfactory/ssh-agent@v0.8.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Build the Keycloak Docker image
      run: docker build ./Keycloack --file ./Keycloack/Dockerfile --tag nuraly/keycloack
    - name: Save the docker image
      run: docker save -o keycloack.tar nuraly/keycloack
    - name : copy to remote
      run: scp -o StrictHostKeyChecking=no  keycloack.tar root@${{ secrets.MAIN_HOST }}:/root/images
    - name : load image into docker
      run: ssh -o StrictHostKeyChecking=no  root@${{ secrets.MAIN_HOST }} "cd /root/images && docker load -i keycloack.tar"

  build_nginx:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: webfactory/ssh-agent@v0.8.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Build the Nfinx Docker image
      run: docker build --build-arg DOMAIN=${{ secrets.HOST_DOMAIN }} ./Nginx --file ./Nginx/Dockerfile --tag nuraly/nginx
    - name: Save the docker image
      run: docker save -o nginx.tar nuraly/nginx
    - name : copy to remote
      run: scp -o StrictHostKeyChecking=no  nginx.tar root@${{ secrets.MAIN_HOST }}:/root/images
    - name : load image into docker
      run: ssh -o StrictHostKeyChecking=no  root@${{ secrets.MAIN_HOST }} "cd /root/images && docker load -i nginx.tar"
