sonar.projectKey=nuralyio_api
sonar.projectName=Nuraly API
sonar.organization=nuralyio

# Source code
sonar.sources=src

# Exclude test files from analysis
sonar.exclusions=**/*.test.ts,**/*.spec.ts,dist/**,build/**,node_modules/**

# Exclude generated files from duplication analysis
sonar.cpd.exclusions=build/**,dist/**

# Coverage
sonar.typescript.lcov.reportPaths=coverage/lcov.info
