badgeFields:
  container:
    uuid: badge_fields_collapse_container
    name: Badge Fields Container
    style: {}

  collapse:
    uuid: badge_fields_collapse
    title: Badge Properties
    style:
      --hy-collapse-content-small-size-padding: 5px
      --hy-collapse-font-weight: normal
      --hy-collapse-border-radius: 0px
      --hy-collapse-width: 292px
      --hy-collapse-border: none
      --hy-collapse-border-bottom: 1px solid #ccc
      --hy-collapse-local-header-background-color: '#3d3d3d'

  properties:
    - name: count
      label: Count
      type: number
      default: '0'
      width: 80px
      placeholder: 0
      valueHandler:
        ref: componentInput
        params: [count]
      stateHandler:
        ref: inputHandler
        params: [count]
      eventHandlers:
        onChange:
          ref: updateInput
          params: [count, number]

    - name: text
      label: Text
      type: text
      default: ''
      width: 180px
      placeholder: Badge text
      valueHandler:
        ref: componentInput
        params: [text]
      stateHandler:
        ref: inputHandler
        params: [text]
      eventHandlers:
        valueChange:
          ref: updateInput
          params: [text, string]

    - name: dot
      label: Dot Badge
      type: radio
      default: false
      width: 180px
      valueHandler: |
        const selectedComponent = Utils.first(Vars.selectedComponents);
        let currentValue = false;
        let isDisabled = false;
        if (selectedComponent?.input?.dot?.type == 'handler' && selectedComponent?.input?.dot?.value) {
          isDisabled = true;
        } else {
          currentValue = selectedComponent?.input?.dot?.value || false;
        }
        const options = [
          { value: false, icon: 'toggle-off', disabled: isDisabled },
          { value: true, icon: 'toggle-on', disabled: isDisabled }
        ];
        const radioType = 'button';
        return [options, currentValue, radioType];
      eventHandlers:
        changed: |
          const selectedComponent = Utils.first(Vars.selectedComponents);
          if (selectedComponent) {
            updateInput(selectedComponent, 'dot', 'boolean', EventData.value);
          }

    - name: showZero
      label: Show Zero
      type: radio
      default: false
      width: 180px
      valueHandler: |
        const selectedComponent = Utils.first(Vars.selectedComponents);
        let currentValue = false;
        let isDisabled = false;
        if (selectedComponent?.input?.showZero?.type == 'handler' && selectedComponent?.input?.showZero?.value) {
          isDisabled = true;
        } else {
          currentValue = selectedComponent?.input?.showZero?.value || false;
        }
        const options = [
          { value: false, icon: 'toggle-off', disabled: isDisabled },
          { value: true, icon: 'toggle-on', disabled: isDisabled }
        ];
        const radioType = 'button';
        return [options, currentValue, radioType];
      eventHandlers:
        changed: |
          const selectedComponent = Utils.first(Vars.selectedComponents);
          if (selectedComponent) {
            updateInput(selectedComponent, 'showZero', 'boolean', EventData.value);
          }

    - name: overflowCount
      label: Overflow Count
      type: number
      default: '99'
      width: 80px
      placeholder: 99
      valueHandler:
        ref: componentInput
        params: [overflowCount]
      stateHandler:
        ref: inputHandler
        params: [overflowCount]
      eventHandlers:
        onChange:
          ref: updateInput
          params: [overflowCount, number]

    - name: size
      label: Size
      type: radio
      default: default
      width: 180px
      valueHandler: |
        const selectedComponent = Utils.first(Vars.selectedComponents);
        let currentSize = '';
        let isDisabled = false;
        if (selectedComponent?.input?.size?.type == 'handler' && selectedComponent?.input?.size?.value) {
          isDisabled = true;
        } else {
          currentSize = selectedComponent?.input?.size?.value || 'default';
        }
        const options = [
          { value: 'small', label: 'S', disabled: isDisabled },
          { value: 'default', label: 'M', disabled: isDisabled }
        ];
        const radioType = 'button';
        return [options, currentSize, radioType];
      eventHandlers:
        changed: |
          const selectedComponent = Utils.first(Vars.selectedComponents);
          if (selectedComponent) {
            updateInput(selectedComponent, 'size', 'string', EventData.value);
          }

    - name: color
      label: Color
      type: radio
      default: ''
      width: 180px
      valueHandler: |
        const selectedComponent = Utils.first(Vars.selectedComponents);
        let currentColor = '';
        let isDisabled = false;
        if (selectedComponent?.input?.color?.type == 'handler' && selectedComponent?.input?.color?.value) {
          isDisabled = true;
        } else {
          currentColor = selectedComponent?.input?.color?.value || '';
        }
        const options = [
          { value: '', label: 'Default', disabled: isDisabled },
          { value: 'primary', label: 'Primary', disabled: isDisabled },
          { value: 'success', label: 'Success', disabled: isDisabled },
          { value: 'warning', label: 'Warning', disabled: isDisabled },
          { value: 'danger', label: 'Danger', disabled: isDisabled }
        ];
        const radioType = 'button';
        return [options, currentColor, radioType];
      eventHandlers:
        changed: |
          const selectedComponent = Utils.first(Vars.selectedComponents);
          if (selectedComponent) {
            updateInput(selectedComponent, 'color', 'string', EventData.value);
          }

    - name: status
      label: Status
      type: radio
      default: ''
      width: 180px
      valueHandler: |
        const selectedComponent = Utils.first(Vars.selectedComponents);
        let currentStatus = '';
        let isDisabled = false;
        if (selectedComponent?.input?.status?.type == 'handler' && selectedComponent?.input?.status?.value) {
          isDisabled = true;
        } else {
          currentStatus = selectedComponent?.input?.status?.value || '';
        }
        const options = [
          { value: '', icon: 'ban', disabled: isDisabled },
          { value: 'default', icon: 'circle', disabled: isDisabled },
          { value: 'processing', icon: 'spinner', disabled: isDisabled },
          { value: 'success', icon: 'check-circle', disabled: isDisabled },
          { value: 'error', icon: 'times-circle', disabled: isDisabled },
          { value: 'warning', icon: 'exclamation-circle', disabled: isDisabled }
        ];
        const radioType = 'button';
        return [options, currentStatus, radioType];
      eventHandlers:
        changed: |
          const selectedComponent = Utils.first(Vars.selectedComponents);
          if (selectedComponent) {
            updateInput(selectedComponent, 'status', 'string', EventData.value);
          }

    - name: ribbon
      label: Ribbon
      type: radio
      default: false
      width: 180px
      valueHandler: |
        const selectedComponent = Utils.first(Vars.selectedComponents);
        let currentValue = false;
        let isDisabled = false;
        if (selectedComponent?.input?.ribbon?.type == 'handler' && selectedComponent?.input?.ribbon?.value) {
          isDisabled = true;
        } else {
          currentValue = selectedComponent?.input?.ribbon?.value || false;
        }
        const options = [
          { value: false, icon: 'toggle-off', disabled: isDisabled },
          { value: true, icon: 'toggle-on', disabled: isDisabled }
        ];
        const radioType = 'button';
        return [options, currentValue, radioType];
      eventHandlers:
        changed: |
          const selectedComponent = Utils.first(Vars.selectedComponents);
          if (selectedComponent) {
            updateInput(selectedComponent, 'ribbon', 'boolean', EventData.value);
          }

    - name: ribbonPlacement
      label: Ribbon Position
      type: radio
      default: end
      width: 180px
      valueHandler: |
        const selectedComponent = Utils.first(Vars.selectedComponents);
        let currentPlacement = '';
        let isDisabled = false;
        if (selectedComponent?.input?.ribbonPlacement?.type == 'handler' && selectedComponent?.input?.ribbonPlacement?.value) {
          isDisabled = true;
        } else {
          currentPlacement = selectedComponent?.input?.ribbonPlacement?.value || 'end';
        }
        const options = [
          { value: 'start', icon: 'arrow-left', disabled: isDisabled },
          { value: 'end', icon: 'arrow-right', disabled: isDisabled }
        ];
        const radioType = 'button';
        return [options, currentPlacement, radioType];
      eventHandlers:
        changed: |
          const selectedComponent = Utils.first(Vars.selectedComponents);
          if (selectedComponent) {
            updateInput(selectedComponent, 'ribbonPlacement', 'string', EventData.value);
          }
