package com.nuraly.workflows.monitoring;

import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.DistributionSummary;
import io.micrometer.core.instrument.Gauge;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Timer;
import io.quarkus.runtime.StartupEvent;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Observes;
import jakarta.inject.Inject;
import org.jboss.logging.Logger;

import java.time.Duration;
import java.util.concurrent.atomic.AtomicLong;

/**
 * Metrics service for RAG (Retrieval-Augmented Generation) operations.
 * Exposes Prometheus metrics at /q/metrics endpoint.
 *
 * Key metrics:
 * - rag.embeddings.generated (counter): Total embeddings generated by provider
 * - rag.embeddings.duration (timer): Embedding generation latency
 * - rag.documents.loaded (counter): Documents loaded by type
 * - rag.documents.chunks (summary): Chunks per document distribution
 * - rag.vectors.stored (counter): Vectors stored in database
 * - rag.vectors.searched (counter): Vector searches performed
 * - rag.search.duration (timer): Search latency
 * - rag.search.results (summary): Results per search distribution
 */
@ApplicationScoped
public class RagMetricsService {

    private static final Logger LOG = Logger.getLogger(RagMetricsService.class);

    @Inject
    MeterRegistry meterRegistry;

    private final AtomicLong activeEmbeddingRequests = new AtomicLong(0);
    private final AtomicLong activeSearchRequests = new AtomicLong(0);

    void onStart(@Observes StartupEvent ev) {
        registerGauges();
        LOG.info("RAG metrics service initialized");
    }

    private void registerGauges() {
        // Active embedding requests gauge
        Gauge.builder("rag.embeddings.active", activeEmbeddingRequests, AtomicLong::get)
                .description("Number of currently processing embedding requests")
                .register(meterRegistry);

        // Active search requests gauge
        Gauge.builder("rag.search.active", activeSearchRequests, AtomicLong::get)
                .description("Number of currently processing vector search requests")
                .register(meterRegistry);
    }

    // ========================================================================
    // Embedding Metrics
    // ========================================================================

    /**
     * Record embedding generation start.
     */
    public void recordEmbeddingStart() {
        activeEmbeddingRequests.incrementAndGet();
    }

    /**
     * Record embedding generation completion.
     *
     * @param provider Provider name (openai, ollama, local)
     * @param model Model name
     * @param textCount Number of texts embedded
     * @param durationMs Duration in milliseconds
     * @param success Whether the operation succeeded
     */
    public void recordEmbeddingComplete(String provider, String model, int textCount,
                                         long durationMs, boolean success) {
        activeEmbeddingRequests.decrementAndGet();

        // Counter for total embeddings
        meterRegistry.counter("rag.embeddings.generated",
                "provider", provider,
                "model", model,
                "status", success ? "success" : "failure")
                .increment(textCount);

        // Timer for latency
        meterRegistry.timer("rag.embeddings.duration",
                "provider", provider,
                "model", model)
                .record(Duration.ofMillis(durationMs));

        // Distribution of batch sizes
        if (success) {
            meterRegistry.summary("rag.embeddings.batch_size",
                    "provider", provider)
                    .record(textCount);
        }
    }

    /**
     * Record embedding token usage.
     */
    public void recordEmbeddingTokens(String provider, String model, int tokenCount) {
        meterRegistry.counter("rag.embeddings.tokens",
                "provider", provider,
                "model", model)
                .increment(tokenCount);
    }

    // ========================================================================
    // Document Loading Metrics
    // ========================================================================

    /**
     * Record document loaded.
     *
     * @param sourceType Document type (pdf, html, txt, etc.)
     * @param characterCount Number of characters extracted
     * @param durationMs Loading duration
     * @param success Whether loading succeeded
     */
    public void recordDocumentLoaded(String sourceType, int characterCount,
                                      long durationMs, boolean success) {
        meterRegistry.counter("rag.documents.loaded",
                "type", sourceType,
                "status", success ? "success" : "failure")
                .increment();

        if (success) {
            meterRegistry.timer("rag.documents.duration",
                    "type", sourceType)
                    .record(Duration.ofMillis(durationMs));

            meterRegistry.summary("rag.documents.size",
                    "type", sourceType)
                    .record(characterCount);
        }
    }

    // ========================================================================
    // Text Splitting Metrics
    // ========================================================================

    /**
     * Record text splitting operation.
     *
     * @param strategy Splitting strategy (recursive, sentence)
     * @param inputChars Input text length
     * @param chunkCount Number of chunks produced
     * @param durationMs Duration in milliseconds
     */
    public void recordTextSplit(String strategy, int inputChars, int chunkCount, long durationMs) {
        meterRegistry.counter("rag.splits.total",
                "strategy", strategy)
                .increment();

        meterRegistry.summary("rag.splits.chunks",
                "strategy", strategy)
                .record(chunkCount);

        meterRegistry.timer("rag.splits.duration",
                "strategy", strategy)
                .record(Duration.ofMillis(durationMs));
    }

    // ========================================================================
    // Vector Storage Metrics
    // ========================================================================

    /**
     * Record vectors stored.
     *
     * @param collectionName Collection name
     * @param count Number of vectors stored
     * @param durationMs Duration in milliseconds
     * @param success Whether storage succeeded
     */
    public void recordVectorsStored(String collectionName, int count,
                                     long durationMs, boolean success) {
        meterRegistry.counter("rag.vectors.stored",
                "collection", collectionName,
                "status", success ? "success" : "failure")
                .increment(count);

        if (success) {
            meterRegistry.timer("rag.vectors.store_duration",
                    "collection", collectionName)
                    .record(Duration.ofMillis(durationMs));
        }
    }

    /**
     * Record vectors deleted.
     */
    public void recordVectorsDeleted(String collectionName, int count) {
        meterRegistry.counter("rag.vectors.deleted",
                "collection", collectionName)
                .increment(count);
    }

    // ========================================================================
    // Vector Search Metrics
    // ========================================================================

    /**
     * Record search start.
     */
    public void recordSearchStart() {
        activeSearchRequests.incrementAndGet();
    }

    /**
     * Record vector search completion.
     *
     * @param collectionName Collection searched
     * @param resultCount Number of results returned
     * @param durationMs Search duration
     * @param success Whether search succeeded
     */
    public void recordSearchComplete(String collectionName, int resultCount,
                                       long durationMs, boolean success) {
        activeSearchRequests.decrementAndGet();

        meterRegistry.counter("rag.search.total",
                "collection", collectionName,
                "status", success ? "success" : "failure")
                .increment();

        if (success) {
            meterRegistry.timer("rag.search.duration",
                    "collection", collectionName)
                    .record(Duration.ofMillis(durationMs));

            meterRegistry.summary("rag.search.results",
                    "collection", collectionName)
                    .record(resultCount);
        }
    }

    // ========================================================================
    // Context Building Metrics
    // ========================================================================

    /**
     * Record context building operation.
     *
     * @param documentsUsed Number of documents included in context
     * @param estimatedTokens Estimated token count of context
     * @param durationMs Duration in milliseconds
     */
    public void recordContextBuilt(int documentsUsed, int estimatedTokens, long durationMs) {
        meterRegistry.counter("rag.context.built").increment();

        meterRegistry.summary("rag.context.documents")
                .record(documentsUsed);

        meterRegistry.summary("rag.context.tokens")
                .record(estimatedTokens);

        meterRegistry.timer("rag.context.duration")
                .record(Duration.ofMillis(durationMs));
    }

    // ========================================================================
    // Utility Methods
    // ========================================================================

    /**
     * Get current active embedding request count.
     */
    public long getActiveEmbeddingCount() {
        return activeEmbeddingRequests.get();
    }

    /**
     * Get current active search request count.
     */
    public long getActiveSearchCount() {
        return activeSearchRequests.get();
    }
}
