upstream front {
    server nuraly_frontend:4321;
}

upstream services-api {
    server host.docker.internal:8081;;
}


upstream keycloak-server {
    server ec2-35-158-240-11.eu-central-1.compute.amazonaws.com:8080;
}
