upstream front {
    server host.docker.internal:4321;
}

upstream services-api {
    server nuraly_services:8081;
}
upstream functions-api {
    server host.docker.internal:7001;
}

upstream keycloak-server {
    server keycloak:8080;
}
