upstream front {
    server host.docker.internal:4321;
}

upstream services-api {
    server nuraly_services:8081;
}
upstream functions-api {
    server host.docker.internal:7001;
}

upstream agent-api {
    server host.docker.internal:7003;
}

upstream keycloak-server {
    server keycloak:8080;
}

upstream copilot-server {
    server copilot:6070;
}

upstream storage-server-api {
    server storage:7004;
}

upstream storage-server {
    server host.docker.internal:9000;
}
