upstream front {
    server studio:4321;
}

upstream services-api {
    server api:8000;
}

upstream functions-api {
    server functions:9000;
}

upstream kv-api {
    server kv:7003;
}

upstream conduit-api {
    server conduit:7004;
}

upstream textlens-api {
    server textlens-api:7006;
}

upstream workflows-api {
    server workflows:7002;
}

# Commented out - not available in dev environment
# upstream agent-api {
#     server host.docker.internal:7003;
# }

upstream keycloak-server {
    server keycloak:8080;
}

# Commented out - not available in dev environment
# upstream copilot-server {
#     server copilot:6070;
# }

# Commented out - not available in dev environment
# upstream storage-server-api {
#     server host.docker.internal:7004;
# }

# Commented out - not available in dev environment
# upstream storage-server {
#     server host.docker.internal:9000;
# }



